# Generated by Django 5.1.3 on 2025-01-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_bankaccount_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                ],
                default="USD",
                help_text="User's preferred currency",
                max_length=3,
            ),
        ),
    ]
