# Generated by Django 5.1.3 on 2025-01-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="next_cursor",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="plaid_token",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="next_cursor",
            field=models.TextField(
                blank=True, help_text="Cursor for fetching transactions", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_plaid_token",
            field=models.CharField(
                blank=True,
                help_text="Access token for latest linked bank accounts",
                max_length=255,
                null=True,
            ),
        ),
    ]
