# Generated by Django 5.1.3 on 2025-01-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_profile_next_cursor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("NGN", "Nigerian Naira"),
                ],
                default="USD",
                help_text="User's preferred currency",
                max_length=3,
            ),
        ),
    ]
