# Generated by Django 5.1.3 on 2025-02-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "is_expense",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category represents an expense (False for Income, Transfer In)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "primary categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is active and available for use",
                    ),
                ),
                (
                    "budget_recommended",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category should be included in budget recommendations",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "sub categories",
                "ordering": ["category", "name"],
                "unique_together": {("name", "category")},
            },
        ),
    ]
