# Generated by Django 5.1.3 on 2025-02-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "primary categories"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["category", "name"],
                "verbose_name_plural": "sub categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="is_expense",
            field=models.BooleanField(
                default=True,
                help_text="Whether this category represents an expense (False for Income, Transfer In)",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="budget_recommended",
            field=models.BooleanField(
                default=True,
                help_text="Whether this category should be included in budget recommendations",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this category is active and available for use",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
