# Generated by Django 5.1.3 on 2025-02-10 13:19

import apps.transactions.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0007_alter_profile_currency"),
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("merchant", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("transaction_date", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "store_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                apps.transactions.mixins.TransactionEmbeddingMixin,
                apps.transactions.mixins.RecurringTransactionMixin,
                apps.transactions.mixins.VectorDocumentMixin,
            ),
        ),
        migrations.CreateModel(
            name="StoreItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "subcategories",
                    models.ManyToManyField(
                        related_name="store_items", to="categories.subcategory"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="transactions.storetransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("merchant", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("transaction_date", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Account balance after transaction",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.bankaccount",
                    ),
                ),
                ("subcategories", models.ManyToManyField(to="categories.subcategory")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["transaction_date"],
                        name="transaction_transac_76bf57_idx",
                    ),
                    models.Index(
                        fields=["merchant"], name="transaction_merchan_b9071c_idx"
                    ),
                ],
            },
            bases=(
                models.Model,
                apps.transactions.mixins.TransactionEmbeddingMixin,
                apps.transactions.mixins.RecurringTransactionMixin,
                apps.transactions.mixins.VectorDocumentMixin,
            ),
        ),
        migrations.CreateModel(
            name="ManualTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("merchant", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("transaction_date", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subcategories", models.ManyToManyField(to="categories.subcategory")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["transaction_date"],
                        name="transaction_transac_097fb5_idx",
                    ),
                    models.Index(
                        fields=["merchant"], name="transaction_merchan_1aa781_idx"
                    ),
                ],
            },
            bases=(
                models.Model,
                apps.transactions.mixins.TransactionEmbeddingMixin,
                apps.transactions.mixins.RecurringTransactionMixin,
                apps.transactions.mixins.VectorDocumentMixin,
            ),
        ),
        migrations.AddIndex(
            model_name="storetransaction",
            index=models.Index(
                fields=["transaction_date"], name="transaction_transac_ddf7ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storetransaction",
            index=models.Index(
                fields=["merchant"], name="transaction_merchan_d48d64_idx"
            ),
        ),
    ]
