# Generated by Django 5.1.3 on 2025-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
