# Generated by Django 5.1.3 on 2025-01-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_bankaccount_user"),
        ("transactions", "0002_alter_banktransaction_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="bank_account",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.bankaccount",
            ),
            preserve_default=False,
        ),
    ]
