# Generated by Django 5.1.3 on 2025-01-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transactions",
            "0004_banktransaction_merchant_storetransaction_merchant_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransaction",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Account balance after transaction",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default="expense",
                max_length=7,
            ),
        ),
    ]
