# Generated by Django 5.1.3 on 2025-02-04 14:34

import apps.transactions.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "categories",
            "0002_alter_category_options_alter_subcategory_options_and_more",
        ),
        (
            "transactions",
            "0006_remove_banktransaction_transaction_type_f26495_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("merchant", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("transaction_date", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subcategories", models.ManyToManyField(to="categories.subcategory")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["transaction_date"],
                        name="transaction_transac_097fb5_idx",
                    ),
                    models.Index(
                        fields=["merchant"], name="transaction_merchan_1aa781_idx"
                    ),
                ],
            },
            bases=(
                models.Model,
                apps.transactions.mixins.TransactionEmbeddingMixin,
                apps.transactions.mixins.RecurringTransactionMixin,
                apps.transactions.mixins.VectorDocumentMixin,
            ),
        ),
    ]
