# Generated by Django 5.1.3 on 2025-02-04 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_manualtransaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storetransaction",
            old_name="store_name",
            new_name="store_location",
        ),
    ]
