# Generated by Django 5.1.3 on 2025-02-04 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0001_initial"),
        (
            "categories",
            "0002_alter_category_options_alter_subcategory_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"ordering": ["-month", "category__name"]},
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "category", "month")},
        ),
        migrations.AddField(
            model_name="budget",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default="2025-12-12"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budget",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="rollover_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Unused amount from previous month's budget",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("on_track", "On Track"),
                    ("warning", "Warning"),
                    ("over_budget", "Over Budget"),
                    ("completed", "Completed"),
                ],
                default="on_track",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount needed for this savings goal",
                        max_digits=10,
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current amount saved towards this goal",
                        max_digits=10,
                    ),
                ),
                (
                    "target_date",
                    models.DateField(help_text="Target date to reach the savings goal"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")], default=1
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "target_date"],
            },
        ),
        migrations.RemoveField(
            model_name="budget",
            name="auto_adjust",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="is_fixed_expense",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="last_updated",
        ),
    ]
