# Generated by Django 5.1.3 on 2025-02-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_alter_budget_options_alter_budget_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsgoal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
